### ISSUE TITLE
config.json dors not exists

### ISSUE THREAD

**Issue by osmanrahimi** [FoundatioFx/Foundatio.Samples#1]
I tried to run the sample project, but unfortunately, there is no such file like `config.json`. 
Is it possible to share an example of this file?

**Comment by niemyjski** [comment]
Hello,

We need to update the sample to the latest version of .net core as it's still running on .net full framework, it's crazy out of date :\

**Comment by niemyjski** [comment]
I'm going to close this as this sample is out of date and Needs to be updated.
